part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const USER_TYPE = _Paths.USER_TYPE;
  static const LOGIN = _Paths.LOGIN;
  static const OTP_VERIFICATION = _Paths.OTP_VERIFICATION;
  static const NAV_BAR = _Paths.NAV_BAR;
  static const HOME = _Paths.HOME;
  static const BOOKING = _Paths.BOOKING;
  static const CHAT = _Paths.CHAT;
  static const PROFILE = _Paths.PROFILE;
  static const MAP = _Paths.MAP;
  static const SEARVICE_FORM = _Paths.SEARVICE_FORM;
  static const SERVICE_PROVIDERS = _Paths.SERVICE_PROVIDERS;
  static const SERVICE_PROVIDERS_DETAILS = _Paths.SERVICE_PROVIDERS_DETAILS;
  static const WAITING_REQUEST = _Paths.WAITING_REQUEST;
  static const TYPING = _Paths.TYPING;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const NOTIFICATION_SETTING = _Paths.NOTIFICATION_SETTING;
  static const CONTACT_US = _Paths.CONTACT_US;
  static const SUPPORT = _Paths.SUPPORT;
  static const ABOUT_US = _Paths.ABOUT_US;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const CREATE_YOUR_PROFILE = _Paths.CREATE_YOUR_PROFILE;
  static const PROVIDER_NAV_BAR = _Paths.PROVIDER_NAV_BAR;
  static const PROVIDER_HOME = _Paths.PROVIDER_HOME;
  static const PROVIDER_BOOKING = _Paths.PROVIDER_BOOKING;
  static const PROVIDER_PROFILE = _Paths.PROVIDER_PROFILE;
  static const PROVIDER_WALLET = _Paths.PROVIDER_WALLET;
  static const PROVIDER_PROJECT_DETAIL = _Paths.PROVIDER_PROJECT_DETAIL;
  static const PROVIDER_MAP = _Paths.PROVIDER_MAP;
  static const PROVIDER_WORKING_PROCESS = _Paths.PROVIDER_WORKING_PROCESS;
  static const PAYMENT = _Paths.PAYMENT;
  static const MOBILE_TRANSFER = _Paths.MOBILE_TRANSFER;
  static const PROVIDER_DOCUMERNT = _Paths.PROVIDER_DOCUMERNT;
  static const BOOKING_TACKING = _Paths.BOOKING_TACKING;
  static const ADD_REVIEW = _Paths.ADD_REVIEW;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const PROVIDER_EDIT_PROFILE = _Paths.PROVIDER_EDIT_PROFILE;
  static const WEB_VIEW_PAYMENT = _Paths.WEB_VIEW_PAYMENT;
  static const BOOKING_SUCESS_POP_UP = _Paths.BOOKING_SUCESS_POP_UP;
  static const BOOKING_DETAILS_USER = _Paths.BOOKING_DETAILS_USER;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const USER_TYPE = '/user-type';
  static const LOGIN = '/login';
  static const OTP_VERIFICATION = '/otp-verification';
  static const NAV_BAR = '/nav-bar';
  static const HOME = '/home';
  static const BOOKING = '/booking';
  static const CHAT = '/chat';
  static const PROFILE = '/profile';
  static const MAP = '/map';
  static const SEARVICE_FORM = '/searvice-form';
  static const SERVICE_PROVIDERS = '/service-providers';
  static const SERVICE_PROVIDERS_DETAILS = '/service-providers-details';
  static const WAITING_REQUEST = '/waiting-request';
  static const TYPING = '/typing';
  static const EDIT_PROFILE = '/edit-profile';
  static const NOTIFICATION_SETTING = '/notification-setting';
  static const CONTACT_US = '/contact-us';
  static const SUPPORT = '/support';
  static const ABOUT_US = '/about-us';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const CREATE_YOUR_PROFILE = '/create-your-profile';
  static const PROVIDER_NAV_BAR = '/provider-nav-bar';
  static const PROVIDER_HOME = '/provider-home';
  static const PROVIDER_BOOKING = '/provider-booking';
  static const PROVIDER_PROFILE = '/provider-profile';
  static const PROVIDER_WALLET = '/provider-wallet';
  static const PROVIDER_PROJECT_DETAIL = '/provider-project-detail';
  static const PROVIDER_MAP = '/provider-map';
  static const PROVIDER_WORKING_PROCESS = '/provider-working-process';
  static const PAYMENT = '/payment';
  static const MOBILE_TRANSFER = '/mobile-transfer';
  static const PROVIDER_DOCUMERNT = '/provider-documernt';
  static const BOOKING_TACKING = '/booking-tacking';
  static const ADD_REVIEW = '/add-review';
  static const NOTIFICATION = '/notification';
  static const PROVIDER_EDIT_PROFILE = '/provider-edit-profile';
  static const WEB_VIEW_PAYMENT = '/web-view-payment';
  static const BOOKING_SUCESS_POP_UP = '/booking-sucess-pop-up';
  static const BOOKING_DETAILS_USER = '/booking-details-user';
}
